[phases.setup]
aptPkgs = ['...', 'python2', 'g++', 'sqlite3']

[phases.build]
builder = 'NIXPACKS'
buildCommand = 'npm run setup'

[phases.deploy]
startCommand = 'npm run start'
restartPolicyType = 'ON_FAILURE'
restartPolicyMaxRetries = 10
