[phases.setup]
aptPkgs = ['...', 'python2', 'g++']

[phases.build]
builder = 'NIXPACKS'
buildCommand = 'npm run before-build'

[phases.deploy]
startCommand = 'npm run start'
restartPolicyType = 'ON_FAILURE'
restartPolicyMaxRetries = 10
