[setup]
aptPkgs = ['...', 'python']

[install]
cmd = "npm run i"

[build]
builder = "NIXPACKS"
buildCommand = "npm run before-build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
